In [1]:
import pandas as pd
import csv
from factor_analyzer import FactorAnalyzer
df=pd.read_csv("/users/nannanliu/Research/MD/MD Chinese.csv", quoting=csv.QUOTE_NONE)

In [2]:
df

features    AMP   ANDC   AWL     BE  BYPA  CAUS  CONC  COND  \
0         reportage   7.19  16.13  1.64   9.59  1.72  2.09  0.56  0.77   
1        editorials   8.49  15.80  1.63  14.88  2.58  3.95  0.89  1.91   
2           reviews   8.74  19.39  1.59  14.67  2.17  3.90  0.89  0.91   
3          religion   8.30  16.10  1.44  16.05  2.56  6.77  0.65  1.77   
4            skills  10.91  15.22  1.56  10.76  1.09  6.44  0.30  2.12   
5           popular  11.15  11.66  1.47  16.08  2.50  3.96  0.72  2.09   
6       biographies  11.81  12.22  1.46  14.23  2.19  5.14  0.98  1.26   
7          official   3.35  25.50  1.73   2.81  0.41  0.62  0.03  0.06   
8          academic   7.40  26.99  1.65  10.92  1.97  5.17  0.55  0.78   
9   general_fiction  11.51   7.04  1.41  18.02  1.93  3.10  0.70  1.37   
10  mystery_fiction  12.49   6.27  1.36  14.43  2.54  2.96  0.63  1.14   
11           sci_fi   8.65   9.19  1.44  11.64  3.06  2.86  0.68  0.61   
12        adventure  11.21   7.29  1.37  14.78  2.57  2.76  0.92  1.75   
13          romance  11.90   6.42  1.39  15.31  2.36  2.74  0.52  1.67   
14            humor  12.42   4.60  1.41  17.88  1.90  3.48  0.45  1.31   

    CONJ_OSUB   ...     modifying_markers  disposal_marker   PEAS  \
0        8.07   ...                 44.02             3.26   8.58   
1       12.41   ...                 54.57             3.13   7.06   
2       10.97   ...                 62.10             2.55  10.62   
3       12.79   ...                 55.20             2.44   8.69   
4       10.81   ...                 51.04             4.03   2.50   
5       12.10   ...                 59.33             3.07  12.37   
6       11.49   ...                 60.26             2.84  13.04   
7        4.08   ...                 30.13             2.57   1.87   
8        9.41   ...                 63.81             2.79   5.77   
9       12.56   ...                 49.71             3.07  13.29   
10      11.13   ...                 51.86             2.92  16.29   
11      14.43   ...                 59.74             4.48  14.61   
12      14.37   ...                 51.41             3.39  15.17   
13      11.61   ...                 51.34             3.29  16.71   
14      10.39   ...                 35.65             3.35  11.64   

    Imperfect_aspect  onomatopoeia  descriptive  similie  dialect  idioms  \
0              12.33          0.15         0.95     0.58     0.00   30.05   
1              11.76          0.03         0.83     0.58     0.00   44.03   
2              13.76          0.10         0.86     1.59     0.00   29.87   
3              11.29          0.33         1.55     2.49     0.33   30.87   
4              11.82          0.15         0.68     1.13     0.00   20.22   
5              17.56          0.45         2.37     2.60     0.07   39.37   
6              16.31          0.28         2.12     2.59     0.09   40.66   
7               6.05          0.03         0.12     0.14     0.00   13.80   
8              10.59          0.50         0.39     1.21     0.02   24.67   
9              17.34          0.98         2.51     4.24     0.10   37.80   
10             18.15          0.90         3.46     2.77     0.03   36.30   
11             18.45          0.76         4.22     3.58     0.00   26.04   
12             19.90          1.03         4.55     3.08     0.03   35.85   
13             20.12          0.99         3.61     3.49     0.10   40.68   
14             14.95          0.52         1.58     1.63     0.14   30.88   

    english  
0      1.33  
1      0.89  
2      0.99  
3      0.57  
4      2.71  
5      1.32  
6      0.70  
7      2.32  
8      7.83  
9      0.69  
10     0.63  
11     1.97  
12     0.34  
13     0.48  
14     0.77  

[15 rows x 57 columns]

In [3]:
df.columns

Index(['features', 'AMP', 'ANDC', 'AWL', 'BE', 'BYPA', 'CAUS', 'CONC', 'COND',
       'CONJ_OSUB', 'abbreviations', 'DEMP', 'DPAR', 'DWNT', 'EMPH', 'EX',
       'FPP', 'HDG', 'INPR', 'JJ', 'NEMD', 'KEMD', 'MOMD', 'NN', 'NOMZ', 'SPP',
       'PHC', 'PIN', 'BPIN', 'PLACE', 'PIRV', 'PUBV', 'RB', 'SMP', 'negation',
       'TIME', 'TPP', 'STTR', 'WH', 'classical_functional_words',
       'classical_syntax', 'disyllabic_words', 'light_verb',
       'verb_reduplication', 'attributive_adjective', 'particles',
       'classifier', 'modifying_markers', 'disposal_marker', 'PEAS',
       'Imperfect_aspect', 'onomatopoeia', 'descriptive', 'similie', 'dialect',
       'idioms', 'english'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 57 columns):
features                      15 non-null object
AMP                           15 non-null float64
ANDC                          15 non-null float64
AWL                           15 non-null float64
BE                            15 non-null float64
BYPA                          15 non-null float64
CAUS                          15 non-null float64
CONC                          15 non-null float64
COND                          15 non-null float64
CONJ_OSUB                     15 non-null float64
abbreviations                 15 non-null float64
DEMP                          15 non-null float64
DPAR                          15 non-null float64
DWNT                          15 non-null float64
EMPH                          15 non-null float64
EX                            15 non-null float64
FPP                           15 non-null float64
HDG                           15 non-null float6

In [5]:
new_df=df.drop(['features'], axis=1)

In [6]:
new_df

AMP   ANDC   AWL     BE  BYPA  CAUS  CONC  COND  CONJ_OSUB  \
0    7.19  16.13  1.64   9.59  1.72  2.09  0.56  0.77       8.07   
1    8.49  15.80  1.63  14.88  2.58  3.95  0.89  1.91      12.41   
2    8.74  19.39  1.59  14.67  2.17  3.90  0.89  0.91      10.97   
3    8.30  16.10  1.44  16.05  2.56  6.77  0.65  1.77      12.79   
4   10.91  15.22  1.56  10.76  1.09  6.44  0.30  2.12      10.81   
5   11.15  11.66  1.47  16.08  2.50  3.96  0.72  2.09      12.10   
6   11.81  12.22  1.46  14.23  2.19  5.14  0.98  1.26      11.49   
7    3.35  25.50  1.73   2.81  0.41  0.62  0.03  0.06       4.08   
8    7.40  26.99  1.65  10.92  1.97  5.17  0.55  0.78       9.41   
9   11.51   7.04  1.41  18.02  1.93  3.10  0.70  1.37      12.56   
10  12.49   6.27  1.36  14.43  2.54  2.96  0.63  1.14      11.13   
11   8.65   9.19  1.44  11.64  3.06  2.86  0.68  0.61      14.43   
12  11.21   7.29  1.37  14.78  2.57  2.76  0.92  1.75      14.37   
13  11.90   6.42  1.39  15.31  2.36  2.74  0.52  1.67      11.61   
14  12.42   4.60  1.41  17.88  1.90  3.48  0.45  1.31      10.39   

    abbreviations   ...     modifying_markers  disposal_marker   PEAS  \
0            9.15   ...                 44.02             3.26   8.58   
1            6.85   ...                 54.57             3.13   7.06   
2            4.50   ...                 62.10             2.55  10.62   
3            3.87   ...                 55.20             2.44   8.69   
4            3.31   ...                 51.04             4.03   2.50   
5            3.36   ...                 59.33             3.07  12.37   
6            4.62   ...                 60.26             2.84  13.04   
7           13.42   ...                 30.13             2.57   1.87   
8            5.26   ...                 63.81             2.79   5.77   
9            4.30   ...                 49.71             3.07  13.29   
10           2.12   ...                 51.86             2.92  16.29   
11           2.46   ...                 59.74             4.48  14.61   
12           2.63   ...                 51.41             3.39  15.17   
13           3.33   ...                 51.34             3.29  16.71   
14           3.19   ...                 35.65             3.35  11.64   

    Imperfect_aspect  onomatopoeia  descriptive  similie  dialect  idioms  \
0              12.33          0.15         0.95     0.58     0.00   30.05   
1              11.76          0.03         0.83     0.58     0.00   44.03   
2              13.76          0.10         0.86     1.59     0.00   29.87   
3              11.29          0.33         1.55     2.49     0.33   30.87   
4              11.82          0.15         0.68     1.13     0.00   20.22   
5              17.56          0.45         2.37     2.60     0.07   39.37   
6              16.31          0.28         2.12     2.59     0.09   40.66   
7               6.05          0.03         0.12     0.14     0.00   13.80   
8              10.59          0.50         0.39     1.21     0.02   24.67   
9              17.34          0.98         2.51     4.24     0.10   37.80   
10             18.15          0.90         3.46     2.77     0.03   36.30   
11             18.45          0.76         4.22     3.58     0.00   26.04   
12             19.90          1.03         4.55     3.08     0.03   35.85   
13             20.12          0.99         3.61     3.49     0.10   40.68   
14             14.95          0.52         1.58     1.63     0.14   30.88   

    english  
0      1.33  
1      0.89  
2      0.99  
3      0.57  
4      2.71  
5      1.32  
6      0.70  
7      2.32  
8      7.83  
9      0.69  
10     0.63  
11     1.97  
12     0.34  
13     0.48  
14     0.77  

[15 rows x 56 columns]

In [7]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 56 columns):
AMP                           15 non-null float64
ANDC                          15 non-null float64
AWL                           15 non-null float64
BE                            15 non-null float64
BYPA                          15 non-null float64
CAUS                          15 non-null float64
CONC                          15 non-null float64
COND                          15 non-null float64
CONJ_OSUB                     15 non-null float64
abbreviations                 15 non-null float64
DEMP                          15 non-null float64
DPAR                          15 non-null float64
DWNT                          15 non-null float64
EMPH                          15 non-null float64
EX                            15 non-null float64
FPP                           15 non-null float64
HDG                           15 non-null float64
INPR                          15 non-null float

In [8]:
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
chi_square_value,p_value=calculate_bartlett_sphericity(new_df)
chi_square_value, p_value

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factor_analyzer/factor_analyzer.py:118: RuntimeWarning: divide by zero encountered in log
  statistic = -np.log(corr_det) * (n - 1 - (2 * p + 5) / 6)


(-inf, 0.0)

In [9]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all,kmo_model=calculate_kmo(new_df)
kmo_model

nan

In [28]:
fa = FactorAnalyzer(rotation='promax')
fa.fit(new_df)

FactorAnalyzer(bounds=(0.005, 1), impute='median', is_corr_matrix=False,
        method='minres', n_factors=3, rotation='promax',
        rotation_kwargs={}, use_smc=True)

In [29]:
fa.loadings_

array([[ 0.68160255,  0.09901283,  0.44160447],
       [-0.94684091,  0.10141078, -0.17544743],
       [-0.85519861, -0.11683998, -0.1887256 ],
       [ 0.5877154 ,  0.26967299,  0.31139891],
       [ 0.38434181,  0.75797129, -0.21438445],
       [-0.44212308,  0.48241723,  0.67420694],
       [ 0.15342965,  0.77124862, -0.16367879],
       [ 0.11559401,  0.18046676,  0.78975375],
       [ 0.37780222,  0.67247906,  0.16819516],
       [-0.46778972, -0.46896157, -0.34173059],
       [ 0.76941248,  0.33504742, -0.02325293],
       [ 0.91988552, -0.16362047,  0.15345063],
       [ 0.3133916 ,  0.26798635,  0.55895688],
       [ 0.04428333,  0.62209946, -0.10649906],
       [ 0.597598  ,  0.10040195,  0.52126637],
       [ 0.97642882, -0.34001206,  0.11654942],
       [-0.85515818,  0.09387215,  0.58199233],
       [ 0.98733339, -0.09438375,  0.05706865],
       [-0.6177881 , -0.15756195,  0.62939814],
       [ 0.48026668, -0.36859757,  0.82988528],
       [ 0.02379277,  0.32162195,  0.652

In [30]:
fa.get_communalities()

array([0.66940008, 0.93757366, 0.7806336 , 0.5151022 , 0.76819979,
       0.88275421, 0.64515584, 0.66964121, 0.62325222, 0.55553197,
       0.70479304, 0.89650813, 0.48246377, 0.4003108 , 0.63892255,
       1.0826052 , 1.07882257, 0.98699235, 0.80262993, 1.05522982,
       0.52919707, 1.04295225, 0.92763929, 0.69742939, 1.13688503,
       0.8808858 , 1.07235002, 0.94760658, 0.47489184, 0.99843773,
       0.82846469, 0.75953691, 0.68788766, 0.978629  , 0.1671438 ,
       0.81586187, 0.32817523, 0.84013538, 1.14471481, 0.89871083,
       0.7559383 , 0.90058206, 0.52589084, 0.59238524, 1.06520595,
       0.78436533, 1.16187478, 0.06468307, 0.9350882 , 0.75419606,
       0.63659257, 0.71079451, 0.62944782, 0.16212143, 0.36881506,
       0.42474696])

In [31]:
fa.get_eigenvalues()

(array([ 3.05417030e+01,  7.79339645e+00,  4.89078472e+00,  3.78974474e+00,
         2.23266601e+00,  2.04466378e+00,  1.70275003e+00,  9.14624764e-01,
         5.39885427e-01,  4.97750708e-01,  3.73895026e-01,  2.80390683e-01,
         2.45418904e-01,  1.52325804e-01,  7.73829482e-15,  4.22384448e-15,
         3.19649284e-15,  2.92426403e-15,  2.33078643e-15,  2.27097319e-15,
         1.88725968e-15,  1.77062867e-15,  1.42233215e-15,  1.23790969e-15,
         9.34572662e-16,  8.82467469e-16,  8.74199779e-16,  6.21952448e-16,
         4.18078095e-16,  4.15148570e-16,  3.73848625e-16,  1.88546521e-16,
         1.02570295e-16, -1.82657692e-17, -6.29341711e-17, -1.30895355e-16,
        -1.75750791e-16, -2.22996058e-16, -3.20433872e-16, -4.95484051e-16,
        -5.36188790e-16, -6.17390200e-16, -1.14280028e-15, -1.17169444e-15,
        -1.23605947e-15, -1.37037136e-15, -1.64599976e-15, -1.77992206e-15,
        -2.18980908e-15, -2.19579051e-15, -2.77554521e-15, -2.98920291e-15,
        -3.0

In [20]:
value = float('3.05417030e+01')
"%f" % value

'30.541703'

In [13]:
[i for i in l if i >= 1]

[30.541703,
 7.79339645,
 4.89078472,
 3.78974474,
 2.23266601,
 2.04466378,
 1.70275003]